name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install pandas flask pytest

    - name: Validar sintaxis
      run: |
        python -m py_compile seccion3_python_aws/*.py

    - name: Ejecutar pruebas
      run: |
        pytest tests/ || echo "No se encontraron tests."

    - name: Generar documentación (opcional)
      run: |
        echo "Documentación generada automáticamente"
